const skills = [
    "Adaptability",
    "Agile Methodologies",
    "AJAX",
    "Analytical Thinking",
    "Android Development",
    "Angular",
    "API Development",
    "Artificial Intelligence",
    "Assembly",
    "AWS",
    "Azure",
    "Back-End Development",
    "Bash",
    "Big Data",
    "Blockchain",
    "Bootstrap",
    "Business Analysis",
    "Business Development",
    "Business Intelligence",
    "C",
    "C#",
    "C++",
    "CI/CD",
    "Client Relationship Management",
    "COBOL",
    "Cloud Computing",
    "Coaching",
    "Clojure",
    "Cocoa",
    "Communication",
    "Conflict Resolution",
    "Content Management Systems (CMS)",
    "Continuous Integration",
    "Corporate Strategy",
    "Creativity",
    "Critical Thinking",
    "Crystal",
    "CSS",
    "Customer Relationship Management (CRM)",
    "Customer Service",
    "Cybersecurity",
    "D3.js",
    "Data Analysis",
    "Data Mining",
    "Data Science",
    "Data Warehousing",
    "Database Management",
    "Decision Making",
    "Delegation",
    "Delphi",
    "Django",
    "Docker",
    "E-Commerce",
    "Elixir",
    "Elm",
    "Emotional Intelligence",
    "Erlang",
    "ERP Systems",
    "Express.js",
    "F#",
    "Financial Management",
    "Flask",
    "Fortran",
    "Front-End Development",
    "Git",
    "Go",
    "GraphQL",
    "Groovy",
    "Hadoop",
    "Haskell",
    "HTML",
    "iOS Development",
    "ITIL",
    "Innovation",
    "Information Security",
    "Java",
    "JavaScript",
    "Jenkins",
    "JIRA",
    "JQuery",
    "JSON",
    "Julia",
    "Kotlin",
    "Kubernetes",
    "Laravel",
    "Leadership",
    "Linux Administration",
    "Lisp",
    "Lua",
    "Machine Learning",
    "Marketing",
    "MATLAB",
    "Mentoring",
    "Microsoft Office",
    "Mobile App Development",
    "MongoDB",
    "MySQL",
    "Negotiation",
    "Networking",
    "Node.js",
    "Objective-C",
    "OCaml",
    "Operating Systems",
    "Pascal",
    "Perl",
    "PHP",
    "PostgreSQL",
    "Presentation Skills",
    "Problem-Solving",
    "Prolog",
    "Project Management",
    "Programming",
    "Python",
    "R",
    "React",
    "Redux",
    "REST APIs",
    "Risk Management",
    "Robotics",
    "Ruby",
    "Rust",
    "SaaS",
    "Sales",
    "Scala",
    "Scheme",
    "Scrum",
    "SEO",
    "Shell",
    "Smalltalk",
    "Software Development",
    "Software Testing",
    "Solidity",
    "SQL",
    "SQL Server",
    "Strategic Planning",
    "Swift",
    "Teamwork",
    "Technical Support",
    "Technical Writing",
    "Terraform",
    "Time Management",
    "TypeScript",
    "UI/UX Design",
    "Version Control",
    "Virtual Reality (VR)",
    "Virtualization",
    "Vue.js",
    "WebAssembly",
    "Web Design",
    "Web Development",
    "XML",
    "YAML"
  ];  

export default skills